export const TOGGLE_TIME_SEGMENT = 'TOGGLE_TIME_SEGMENT';
export const CHANGE_PERIOD = 'CHANGE_PERIOD';
export const OPEN_EVENT_FIELD = 'OPEN_EVENT_FIELD';
export const CLOSE_EVENT_FIELD = 'CLOSE_EVENT_FIELD';
export const CHANGE_START_DATE = 'CHANGE_START_DATE';
export const CHANGE_END_DATE = 'CHANGE_END_DATE';
